[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
edition = "2018"

[dependencies]
anyhow = "*"
byteorder = "*"
memmap = "*"
num_cpus = "*"
owning_ref = "*"
png = "*"
tini = "*"
stb_truetype = "*"
xml-rs = "*"
indexmap = "*"

[features]
perf-stats = []

# So that we have line numbers in backtraces with RUST_BACKTRACE=1.
[profile.release]
debug = true
