[package]
name = "renderer"
version = "1.0.0"
authors = ["Ivan Komarov <Ivan.Komarov@dfyz.info>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "*"
byteorder = "*"
memmap = "*"
num_cpus = "*"
owning_ref = "*"
png = "*"
tini = "*"
stb_truetype = "*"
xml-rs = "*"
indexmap = "*"

[dependencies.osmpbf]
version = "*"
optional = true

[features]
perf-stats = []
pbf = ["osmpbf"]

# So that we have line numbers in backtraces with RUST_BACKTRACE=1.
[profile.release]
debug = true
